//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTP.Dict {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTP.Dict.LangStrings", typeof(LangStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number (SN) of the top camera .
        /// </summary>
        internal static string Camera1SN {
            get {
                return ResourceManager.GetString("Camera1SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number (SN) of the side camera .
        /// </summary>
        internal static string Camera2SN {
            get {
                return ResourceManager.GetString("Camera2SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera parameters .
        /// </summary>
        internal static string CameraParam {
            get {
                return ResourceManager.GetString("CameraParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected .
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller IP-address .
        /// </summary>
        internal static string ControllerIP {
            get {
                return ResourceManager.GetString("ControllerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller parameters .
        /// </summary>
        internal static string ControllerParam {
            get {
                return ResourceManager.GetString("ControllerParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from  .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture saved under: \r\n .
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the contents of the clipboard .
        /// </summary>
        internal static string InsertBuffer {
            get {
                return ResourceManager.GetString("InsertBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkm .
        /// </summary>
        internal static string mkm {
            get {
                return ResourceManager.GetString("mkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mm .
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Code uploaded successfull.
        /// </summary>
        internal static string SavedOK {
            get {
                return ResourceManager.GetString("SavedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL .
        /// </summary>
        internal static string StatusManual {
            get {
                return ResourceManager.GetString("StatusManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSED .
        /// </summary>
        internal static string StatusPause {
            get {
                return ResourceManager.GetString("StatusPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNNING .
        /// </summary>
        internal static string StatusRun {
            get {
                return ResourceManager.GetString("StatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOPPED .
        /// </summary>
        internal static string StatusStop {
            get {
                return ResourceManager.GetString("StatusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video saved under: \r\n.
        /// </summary>
        internal static string VideoSaved {
            get {
                return ResourceManager.GetString("VideoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Error in line:.
        /// </summary>
        internal static string WrongCompile {
            get {
                return ResourceManager.GetString("WrongCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:  .
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
